### PR TITLE
added file in /data with real TX physician surnames

### PR DESCRIPTION
**Pull request by vmelf**

### CODE REVIEW

**Comment by SeanKilleen** [comment]
Does this get into a legal grey area in terms of using others' real names for fake submittals? Not sure I like the idea of involving others who don't choose to be involved, and I'm not sure this will add functionality unless somehow names start to be scanned against real names. IMO we should shelve this unless it's absolutely needed.

**Comment by vmelf** [comment]
Totally agree. I figured only using last names and a random first initial could protect them, but I don't think we can be overly cautious either. 

But yeah, the idea behind it was that maybe if they start checking the validity of doctor names, we'd need real ones

**Comment by andria-dev** [comment]
@SeanKilleen This was discussed on Discord, I believe we concluded that the use of real doctor's names was to ensure that people reviewing submissions cannot tell our submissions apart from people who are in Texas since the surnames of the doctors are now relevant.

While I see your concern about involving other's who did not choose to be involved, we are not providing full names, only surnames that multiple people may have. Alongside this, the data being used here is already public information so I personally do not feel like it constitutes any collection or misuse of personal data.

**Comment by vmelf** [comment]
@andria-dev this list has not filtered out unique names. Some are unique enough, I'd imagine there's only one doctor with that name. Would you like me to update this only with repeat names?

**Comment by SeanKilleen** [comment]
> since the surnames of the doctors are now relevant.

I didn't realize this was the case. If the surnames are being checked, then yes, I agree this is the way to go. Otherwise, I'd suggest we keep it in our back pocket.

**Comment by andria-dev** [comment]
@SeanKilleen "now relevant" meaning the use of surnames makes them more realistic to the use case of the form.

@script-kitty-0 We could try that, I meant more that there are other non-Texas doctor people with those last names, likely even the ones that only appear on the list once. But if there are a significant amount of names that show up multiple times we could try that.

**Comment by andria-dev** [comment]
Just calculated it @script-kitty-0, looks like there are 487 surnames on that list that appear at least twice.

**Comment by andria-dev** [comment]
This might be more helpful in the AbBOT-api repo though as we move towards serving all of the random data as api that we spin up separately

**Comment by vmelf** [comment]
will move it over there. thanks Andria!

**Pull request closed without merging**
