### PR TITLE
Dockerize It

### PR DESCRIPTION
**Pull request by SeanKilleen**

### CODE REVIEW

**Comment by andria-dev** [comment]
If this is still a Work In Progress (WIP) can you make it a Draft PR so that it doesn't accidentally get merged. Instructions on how to do so are on the [GitHub docs for changing the stage of a PR](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft).

**Comment by SeanKilleen** [comment]
I'm familiar with the process; I thought you were using WIP bot to avoid auto merge. (may want to look into using that; it's free.)

I'll mark as a draft if that's the preference. 👍

**Comment by SeanKilleen** [comment]
Updates:

* Docker builds and appears to run
* Haven't gotten the chance to use it as designed yet, will check as soon as I get time and am back at the keyboard
* Will consider a follow up PR to pick up some settings (e.g. number of submissions) from ENV variables so they can be set when loading the container.

I welcome additional feedback / contributions on this PR. Feel free to pull, review, suggest or make edits. 👍

**Comment by SeanKilleen** [comment]
I can't get the site to show up in my local browser. I'm decent with Docker but I'm sure I'm screwing up the networking somehow.

As far as I can tell, here's what's happening:

* The web site is being run in the container on localhost:8000
* The  container's hosts file is mapping prolifewhisterblower.com back to its localhost within the container
* I am mapping my own hosts file so that prolifewhistlebower.com goes to localhost

My expectation is:

* I type in the prolifewhistleblower.com:8000 URL
* It gets mapped to localhost:8000 on my machine
* This gets mapped to the container's port 8000
* The site shows up. 

However, this isn't happening. Things are timing out. I'm certain I must be doing something wrong at the networking level.

**Comment by SeanKilleen** [comment]
OK, this is ready to go I think. Feedback welcome on docs etc.

**Comment by SeanKilleen** [comment]
To be clear: I'm still getting failures but I think that's because the site is still down. Anyone is welcome to double-check this though.

**Pull request merged**
